// Country ISO 3166-1 alpha-2 → English name + TORA zone.
// Mirrors tora-backend/src/utils/geo.js, itself limited to the countries the
// app can represent (tora-app src/data/profiles.js). Change there first.

export const ZONES = ['Africa', 'Americas', 'Asia', 'Europe', 'Middle East', 'Oceania'] as const;
export type Zone = (typeof ZONES)[number];

export const COUNTRY_BY_ISO2: Record<string, { name: string; zone: Zone }> = {
  "": { name: "Andorra", zone: "Europe" },
  "": { name: "UAE", zone: "Middle East" },
  "": { name: "Afghanistan", zone: "Middle East" },
  "": { name: "Antigua and Barbuda", zone: "Americas" },
  "": { name: "Albania", zone: "Europe" },
  "": { name: "Armenia", zone: "Europe" },
  "": { name: "Angola", zone: "Africa" },
  "": { name: "Argentina", zone: "Americas" },
  "": { name: "Austria", zone: "Europe" },
  "": { name: "Australia", zone: "Oceania" },
  "": { name: "Azerbaijan", zone: "Europe" },
  "": { name: "Bosnia and Herzegovina", zone: "Europe" },
  "": { name: "Barbados", zone: "Americas" },
  "": { name: "Bangladesh", zone: "Asia" },
  "": { name: "Belgium", zone: "Europe" },
  "": { name: "Burkina Faso", zone: "Africa" },
  "": { name: "Bulgaria", zone: "Europe" },
  "": { name: "Bahrain", zone: "Middle East" },
  "": { name: "Burundi", zone: "Africa" },
  "": { name: "Benin", zone: "Africa" },
  "": { name: "Brunei", zone: "Asia" },
  "": { name: "Bolivia", zone: "Americas" },
  "": { name: "Brazil", zone: "Americas" },
  "": { name: "Bahamas", zone: "Americas" },
  "": { name: "Bhutan", zone: "Asia" },
  "": { name: "Botswana", zone: "Africa" },
  "": { name: "Belarus", zone: "Europe" },
  "": { name: "Belize", zone: "Americas" },
  "": { name: "Canada", zone: "Americas" },
  "": { name: "DR Congo", zone: "Africa" },
  "": { name: "Central African Republic", zone: "Africa" },
  "": { name: "Congo", zone: "Africa" },
  "": { name: "Switzerland", zone: "Europe" },
  "": { name: "Ivory Coast", zone: "Africa" },
  "": { name: "Cook Islands", zone: "Oceania" },
  "": { name: "Chile", zone: "Americas" },
  "": { name: "Cameroon", zone: "Africa" },
  "": { name: "China", zone: "Asia" },
  "": { name: "Colombia", zone: "Americas" },
  "": { name: "Costa Rica", zone: "Americas" },
  "": { name: "Cuba", zone: "Americas" },
  "": { name: "Cabo Verde", zone: "Africa" },
  "": { name: "Cyprus", zone: "Europe" },
  "": { name: "Czech Republic", zone: "Europe" },
  "": { name: "Germany", zone: "Europe" },
  "": { name: "Djibouti", zone: "Africa" },
  "": { name: "Denmark", zone: "Europe" },
  "": { name: "Dominica", zone: "Americas" },
  "": { name: "Dominican Republic", zone: "Americas" },
  "": { name: "Algeria", zone: "Africa" },
  "": { name: "Ecuador", zone: "Americas" },
  "": { name: "Estonia", zone: "Europe" },
  "": { name: "Egypt", zone: "Africa" },
  "": { name: "Eritrea", zone: "Africa" },
  "": { name: "Spain", zone: "Europe" },
  "": { name: "Ethiopia", zone: "Africa" },
  "": { name: "Finland", zone: "Europe" },
  "": { name: "Fiji", zone: "Oceania" },
  "": { name: "Micronesia", zone: "Oceania" },
  "": { name: "France", zone: "Europe" },
  "": { name: "Gabon", zone: "Africa" },
  "": { name: "United Kingdom", zone: "Europe" },
  "": { name: "Grenada", zone: "Americas" },
  "": { name: "Georgia", zone: "Europe" },
  "": { name: "Ghana", zone: "Africa" },
  "": { name: "Gambia", zone: "Africa" },
  "": { name: "Guinea", zone: "Africa" },
  "": { name: "Equatorial Guinea", zone: "Africa" },
  "": { name: "Greece", zone: "Europe" },
  "": { name: "Guatemala", zone: "Americas" },
  "": { name: "Guam", zone: "Oceania" },
  "": { name: "Guinea-Bissau", zone: "Africa" },
  "": { name: "Guyana", zone: "Americas" },
  "": { name: "Hong Kong", zone: "Asia" },
  "": { name: "Honduras", zone: "Americas" },
  "": { name: "Croatia", zone: "Europe" },
  "": { name: "Haiti", zone: "Americas" },
  "": { name: "Hungary", zone: "Europe" },
  "": { name: "Indonesia", zone: "Asia" },
  "": { name: "Ireland", zone: "Europe" },
  "": { name: "Israel", zone: "Middle East" },
  "": { name: "India", zone: "Asia" },
  "": { name: "Iraq", zone: "Middle East" },
  "": { name: "Iran", zone: "Middle East" },
  "": { name: "Iceland", zone: "Europe" },
  "": { name: "Italy", zone: "Europe" },
  "": { name: "Jamaica", zone: "Americas" },
  "": { name: "Jordan", zone: "Middle East" },
  "": { name: "Japan", zone: "Asia" },
  "": { name: "Kenya", zone: "Africa" },
  "": { name: "Kyrgyzstan", zone: "Asia" },
  "": { name: "Cambodia", zone: "Asia" },
  "": { name: "Kiribati", zone: "Oceania" },
  "": { name: "Comoros", zone: "Africa" },
  "": { name: "Saint Kitts and Nevis", zone: "Americas" },
  "": { name: "South Korea", zone: "Asia" },
  "": { name: "Kuwait", zone: "Middle East" },
  "": { name: "Kazakhstan", zone: "Asia" },
  "": { name: "Laos", zone: "Asia" },
  "": { name: "Lebanon", zone: "Middle East" },
  "": { name: "Saint Lucia", zone: "Americas" },
  "": { name: "Liechtenstein", zone: "Europe" },
  "": { name: "Sri Lanka", zone: "Asia" },
  "": { name: "Liberia", zone: "Africa" },
  "": { name: "Lesotho", zone: "Africa" },
  "": { name: "Lithuania", zone: "Europe" },
  "": { name: "Luxembourg", zone: "Europe" },
  "": { name: "Latvia", zone: "Europe" },
  "": { name: "Libya", zone: "Africa" },
  "": { name: "Morocco", zone: "Africa" },
  "": { name: "Monaco", zone: "Europe" },
  "": { name: "Moldova", zone: "Europe" },
  "": { name: "Montenegro", zone: "Europe" },
  "": { name: "Madagascar", zone: "Africa" },
  "": { name: "Marshall Islands", zone: "Oceania" },
  "": { name: "North Macedonia", zone: "Europe" },
  "": { name: "Mali", zone: "Africa" },
  "": { name: "Myanmar", zone: "Asia" },
  "": { name: "Mongolia", zone: "Asia" },
  "": { name: "Macao", zone: "Asia" },
  "": { name: "Mauritania", zone: "Africa" },
  "": { name: "Malta", zone: "Europe" },
  "": { name: "Mauritius", zone: "Africa" },
  "": { name: "Maldives", zone: "Asia" },
  "": { name: "Malawi", zone: "Africa" },
  "": { name: "Mexico", zone: "Americas" },
  "": { name: "Malaysia", zone: "Asia" },
  "": { name: "Mozambique", zone: "Africa" },
  "": { name: "Namibia", zone: "Africa" },
  "": { name: "New Caledonia", zone: "Oceania" },
  "": { name: "Niger", zone: "Africa" },
  "": { name: "Nigeria", zone: "Africa" },
  "": { name: "Nicaragua", zone: "Americas" },
  "": { name: "Netherlands", zone: "Europe" },
  "": { name: "Norway", zone: "Europe" },
  "": { name: "Nepal", zone: "Asia" },
  "": { name: "Nauru", zone: "Oceania" },
  "": { name: "New Zealand", zone: "Oceania" },
  "": { name: "Oman", zone: "Middle East" },
  "": { name: "Panama", zone: "Americas" },
  "": { name: "Peru", zone: "Americas" },
  "": { name: "French Polynesia", zone: "Oceania" },
  "": { name: "Papua New Guinea", zone: "Oceania" },
  "": { name: "Philippines", zone: "Asia" },
  "": { name: "Pakistan", zone: "Asia" },
  "": { name: "Poland", zone: "Europe" },
  "": { name: "Puerto Rico", zone: "Americas" },
  "": { name: "Palestine", zone: "Middle East" },
  "": { name: "Portugal", zone: "Europe" },
  "": { name: "Palau", zone: "Oceania" },
  "": { name: "Paraguay", zone: "Americas" },
  "": { name: "Qatar", zone: "Middle East" },
  "": { name: "Romania", zone: "Europe" },
  "": { name: "Serbia", zone: "Europe" },
  "": { name: "Russia", zone: "Europe" },
  "": { name: "Rwanda", zone: "Africa" },
  "": { name: "Saudi Arabia", zone: "Middle East" },
  "": { name: "Solomon Islands", zone: "Oceania" },
  "": { name: "Seychelles", zone: "Africa" },
  "": { name: "Sudan", zone: "Africa" },
  "": { name: "Sweden", zone: "Europe" },
  "": { name: "Singapore", zone: "Asia" },
  "": { name: "Slovenia", zone: "Europe" },
  "": { name: "Slovakia", zone: "Europe" },
  "": { name: "Sierra Leone", zone: "Africa" },
  "": { name: "San Marino", zone: "Europe" },
  "": { name: "Senegal", zone: "Africa" },
  "": { name: "Somalia", zone: "Africa" },
  "": { name: "Suriname", zone: "Americas" },
  "": { name: "South Sudan", zone: "Africa" },
  "": { name: "Sao Tome and Principe", zone: "Africa" },
  "": { name: "El Salvador", zone: "Americas" },
  "": { name: "Syria", zone: "Middle East" },
  "": { name: "Eswatini", zone: "Africa" },
  "": { name: "Chad", zone: "Africa" },
  "": { name: "Togo", zone: "Africa" },
  "": { name: "Thailand", zone: "Asia" },
  "": { name: "Tajikistan", zone: "Asia" },
  "": { name: "Timor-Leste", zone: "Asia" },
  "": { name: "Turkmenistan", zone: "Asia" },
  "": { name: "Tunisia", zone: "Africa" },
  "": { name: "Tonga", zone: "Oceania" },
  "": { name: "Turkey", zone: "Middle East" },
  "": { name: "Trinidad and Tobago", zone: "Americas" },
  "": { name: "Tuvalu", zone: "Oceania" },
  "": { name: "Taiwan", zone: "Asia" },
  "": { name: "Tanzania", zone: "Africa" },
  "": { name: "Ukraine", zone: "Europe" },
  "": { name: "Uganda", zone: "Africa" },
  "": { name: "United States", zone: "Americas" },
  "": { name: "Uruguay", zone: "Americas" },
  "": { name: "Uzbekistan", zone: "Asia" },
  "": { name: "Saint Vincent and the Grenadines", zone: "Americas" },
  "": { name: "Venezuela", zone: "Americas" },
  "": { name: "Vietnam", zone: "Asia" },
  "": { name: "Vanuatu", zone: "Oceania" },
  "": { name: "Samoa", zone: "Oceania" },
  "": { name: "Kosovo", zone: "Europe" },
  "": { name: "Yemen", zone: "Middle East" },
  "": { name: "South Africa", zone: "Africa" },
  "": { name: "Zambia", zone: "Africa" },
  "": { name: "Zimbabwe", zone: "Africa" },
};

export const COUNTRIES: { code: string; name: string; zone: Zone }[] = Object.entries(COUNTRY_BY_ISO2)
  .map(([code, v]) => ({ code, name: v.name, zone: v.zone }))
  .sort((a, b) => a.name.localeCompare(b.name));
