// Country ISO 3166-1 alpha-2 → English name + TORA zone.
// Mirrors tora-backend/src/utils/geo.js, itself limited to the countries the
// app can represent (tora-app src/data/profiles.js). Change there first.

export const ZONES = ['Africa', 'Americas', 'Asia', 'Europe', 'Middle East', 'Oceania'] as const;
export type Zone = (typeof ZONES)[number];

export const COUNTRY_BY_ISO2: Record<string, { name: string; zone: Zone }> = {
  "AD": { name: "Andorra", zone: "Europe" },
  "AE": { name: "UAE", zone: "Middle East" },
  "AF": { name: "Afghanistan", zone: "Middle East" },
  "AG": { name: "Antigua and Barbuda", zone: "Americas" },
  "AL": { name: "Albania", zone: "Europe" },
  "AM": { name: "Armenia", zone: "Europe" },
  "AO": { name: "Angola", zone: "Africa" },
  "AR": { name: "Argentina", zone: "Americas" },
  "AT": { name: "Austria", zone: "Europe" },
  "AU": { name: "Australia", zone: "Oceania" },
  "AZ": { name: "Azerbaijan", zone: "Europe" },
  "BA": { name: "Bosnia and Herzegovina", zone: "Europe" },
  "BB": { name: "Barbados", zone: "Americas" },
  "BD": { name: "Bangladesh", zone: "Asia" },
  "BE": { name: "Belgium", zone: "Europe" },
  "BF": { name: "Burkina Faso", zone: "Africa" },
  "BG": { name: "Bulgaria", zone: "Europe" },
  "BH": { name: "Bahrain", zone: "Middle East" },
  "BI": { name: "Burundi", zone: "Africa" },
  "BJ": { name: "Benin", zone: "Africa" },
  "BN": { name: "Brunei", zone: "Asia" },
  "BO": { name: "Bolivia", zone: "Americas" },
  "BR": { name: "Brazil", zone: "Americas" },
  "BS": { name: "Bahamas", zone: "Americas" },
  "BT": { name: "Bhutan", zone: "Asia" },
  "BW": { name: "Botswana", zone: "Africa" },
  "BY": { name: "Belarus", zone: "Europe" },
  "BZ": { name: "Belize", zone: "Americas" },
  "CA": { name: "Canada", zone: "Americas" },
  "CD": { name: "DR Congo", zone: "Africa" },
  "CF": { name: "Central African Republic", zone: "Africa" },
  "CG": { name: "Congo", zone: "Africa" },
  "CH": { name: "Switzerland", zone: "Europe" },
  "CI": { name: "Ivory Coast", zone: "Africa" },
  "CK": { name: "Cook Islands", zone: "Oceania" },
  "CL": { name: "Chile", zone: "Americas" },
  "CM": { name: "Cameroon", zone: "Africa" },
  "CN": { name: "China", zone: "Asia" },
  "CO": { name: "Colombia", zone: "Americas" },
  "CR": { name: "Costa Rica", zone: "Americas" },
  "CU": { name: "Cuba", zone: "Americas" },
  "CV": { name: "Cabo Verde", zone: "Africa" },
  "CY": { name: "Cyprus", zone: "Europe" },
  "CZ": { name: "Czech Republic", zone: "Europe" },
  "DE": { name: "Germany", zone: "Europe" },
  "DJ": { name: "Djibouti", zone: "Africa" },
  "DK": { name: "Denmark", zone: "Europe" },
  "DM": { name: "Dominica", zone: "Americas" },
  "DO": { name: "Dominican Republic", zone: "Americas" },
  "DZ": { name: "Algeria", zone: "Africa" },
  "EC": { name: "Ecuador", zone: "Americas" },
  "EE": { name: "Estonia", zone: "Europe" },
  "EG": { name: "Egypt", zone: "Africa" },
  "ER": { name: "Eritrea", zone: "Africa" },
  "ES": { name: "Spain", zone: "Europe" },
  "ET": { name: "Ethiopia", zone: "Africa" },
  "FI": { name: "Finland", zone: "Europe" },
  "FJ": { name: "Fiji", zone: "Oceania" },
  "FM": { name: "Micronesia", zone: "Oceania" },
  "FR": { name: "France", zone: "Europe" },
  "GA": { name: "Gabon", zone: "Africa" },
  "GB": { name: "United Kingdom", zone: "Europe" },
  "GD": { name: "Grenada", zone: "Americas" },
  "GE": { name: "Georgia", zone: "Europe" },
  "GH": { name: "Ghana", zone: "Africa" },
  "GM": { name: "Gambia", zone: "Africa" },
  "GN": { name: "Guinea", zone: "Africa" },
  "GQ": { name: "Equatorial Guinea", zone: "Africa" },
  "GR": { name: "Greece", zone: "Europe" },
  "GT": { name: "Guatemala", zone: "Americas" },
  "GU": { name: "Guam", zone: "Oceania" },
  "GW": { name: "Guinea-Bissau", zone: "Africa" },
  "GY": { name: "Guyana", zone: "Americas" },
  "HK": { name: "Hong Kong", zone: "Asia" },
  "HN": { name: "Honduras", zone: "Americas" },
  "HR": { name: "Croatia", zone: "Europe" },
  "HT": { name: "Haiti", zone: "Americas" },
  "HU": { name: "Hungary", zone: "Europe" },
  "ID": { name: "Indonesia", zone: "Asia" },
  "IE": { name: "Ireland", zone: "Europe" },
  "IL": { name: "Israel", zone: "Middle East" },
  "IN": { name: "India", zone: "Asia" },
  "IQ": { name: "Iraq", zone: "Middle East" },
  "IR": { name: "Iran", zone: "Middle East" },
  "IS": { name: "Iceland", zone: "Europe" },
  "IT": { name: "Italy", zone: "Europe" },
  "JM": { name: "Jamaica", zone: "Americas" },
  "JO": { name: "Jordan", zone: "Middle East" },
  "JP": { name: "Japan", zone: "Asia" },
  "KE": { name: "Kenya", zone: "Africa" },
  "KG": { name: "Kyrgyzstan", zone: "Asia" },
  "KH": { name: "Cambodia", zone: "Asia" },
  "KI": { name: "Kiribati", zone: "Oceania" },
  "KM": { name: "Comoros", zone: "Africa" },
  "KN": { name: "Saint Kitts and Nevis", zone: "Americas" },
  "KR": { name: "South Korea", zone: "Asia" },
  "KW": { name: "Kuwait", zone: "Middle East" },
  "KZ": { name: "Kazakhstan", zone: "Asia" },
  "LA": { name: "Laos", zone: "Asia" },
  "LB": { name: "Lebanon", zone: "Middle East" },
  "LC": { name: "Saint Lucia", zone: "Americas" },
  "LI": { name: "Liechtenstein", zone: "Europe" },
  "LK": { name: "Sri Lanka", zone: "Asia" },
  "LR": { name: "Liberia", zone: "Africa" },
  "LS": { name: "Lesotho", zone: "Africa" },
  "LT": { name: "Lithuania", zone: "Europe" },
  "LU": { name: "Luxembourg", zone: "Europe" },
  "LV": { name: "Latvia", zone: "Europe" },
  "LY": { name: "Libya", zone: "Africa" },
  "MA": { name: "Morocco", zone: "Africa" },
  "MC": { name: "Monaco", zone: "Europe" },
  "MD": { name: "Moldova", zone: "Europe" },
  "ME": { name: "Montenegro", zone: "Europe" },
  "MG": { name: "Madagascar", zone: "Africa" },
  "MH": { name: "Marshall Islands", zone: "Oceania" },
  "MK": { name: "North Macedonia", zone: "Europe" },
  "ML": { name: "Mali", zone: "Africa" },
  "MM": { name: "Myanmar", zone: "Asia" },
  "MN": { name: "Mongolia", zone: "Asia" },
  "MO": { name: "Macao", zone: "Asia" },
  "MR": { name: "Mauritania", zone: "Africa" },
  "MT": { name: "Malta", zone: "Europe" },
  "MU": { name: "Mauritius", zone: "Africa" },
  "MV": { name: "Maldives", zone: "Asia" },
  "MW": { name: "Malawi", zone: "Africa" },
  "MX": { name: "Mexico", zone: "Americas" },
  "MY": { name: "Malaysia", zone: "Asia" },
  "MZ": { name: "Mozambique", zone: "Africa" },
  "NA": { name: "Namibia", zone: "Africa" },
  "NC": { name: "New Caledonia", zone: "Oceania" },
  "NE": { name: "Niger", zone: "Africa" },
  "NG": { name: "Nigeria", zone: "Africa" },
  "NI": { name: "Nicaragua", zone: "Americas" },
  "NL": { name: "Netherlands", zone: "Europe" },
  "NO": { name: "Norway", zone: "Europe" },
  "NP": { name: "Nepal", zone: "Asia" },
  "NR": { name: "Nauru", zone: "Oceania" },
  "NZ": { name: "New Zealand", zone: "Oceania" },
  "OM": { name: "Oman", zone: "Middle East" },
  "PA": { name: "Panama", zone: "Americas" },
  "PE": { name: "Peru", zone: "Americas" },
  "PF": { name: "French Polynesia", zone: "Oceania" },
  "PG": { name: "Papua New Guinea", zone: "Oceania" },
  "PH": { name: "Philippines", zone: "Asia" },
  "PK": { name: "Pakistan", zone: "Asia" },
  "PL": { name: "Poland", zone: "Europe" },
  "PR": { name: "Puerto Rico", zone: "Americas" },
  "PS": { name: "Palestine", zone: "Middle East" },
  "PT": { name: "Portugal", zone: "Europe" },
  "PW": { name: "Palau", zone: "Oceania" },
  "PY": { name: "Paraguay", zone: "Americas" },
  "QA": { name: "Qatar", zone: "Middle East" },
  "RO": { name: "Romania", zone: "Europe" },
  "RS": { name: "Serbia", zone: "Europe" },
  "RU": { name: "Russia", zone: "Europe" },
  "RW": { name: "Rwanda", zone: "Africa" },
  "SA": { name: "Saudi Arabia", zone: "Middle East" },
  "SB": { name: "Solomon Islands", zone: "Oceania" },
  "SC": { name: "Seychelles", zone: "Africa" },
  "SD": { name: "Sudan", zone: "Africa" },
  "SE": { name: "Sweden", zone: "Europe" },
  "SG": { name: "Singapore", zone: "Asia" },
  "SI": { name: "Slovenia", zone: "Europe" },
  "SK": { name: "Slovakia", zone: "Europe" },
  "SL": { name: "Sierra Leone", zone: "Africa" },
  "SM": { name: "San Marino", zone: "Europe" },
  "SN": { name: "Senegal", zone: "Africa" },
  "SO": { name: "Somalia", zone: "Africa" },
  "SR": { name: "Suriname", zone: "Americas" },
  "SS": { name: "South Sudan", zone: "Africa" },
  "ST": { name: "Sao Tome and Principe", zone: "Africa" },
  "SV": { name: "El Salvador", zone: "Americas" },
  "SY": { name: "Syria", zone: "Middle East" },
  "SZ": { name: "Eswatini", zone: "Africa" },
  "TD": { name: "Chad", zone: "Africa" },
  "TG": { name: "Togo", zone: "Africa" },
  "TH": { name: "Thailand", zone: "Asia" },
  "TJ": { name: "Tajikistan", zone: "Asia" },
  "TL": { name: "Timor-Leste", zone: "Asia" },
  "TM": { name: "Turkmenistan", zone: "Asia" },
  "TN": { name: "Tunisia", zone: "Africa" },
  "TO": { name: "Tonga", zone: "Oceania" },
  "TR": { name: "Turkey", zone: "Middle East" },
  "TT": { name: "Trinidad and Tobago", zone: "Americas" },
  "TV": { name: "Tuvalu", zone: "Oceania" },
  "TW": { name: "Taiwan", zone: "Asia" },
  "TZ": { name: "Tanzania", zone: "Africa" },
  "UA": { name: "Ukraine", zone: "Europe" },
  "UG": { name: "Uganda", zone: "Africa" },
  "US": { name: "United States", zone: "Americas" },
  "UY": { name: "Uruguay", zone: "Americas" },
  "UZ": { name: "Uzbekistan", zone: "Asia" },
  "VC": { name: "Saint Vincent and the Grenadines", zone: "Americas" },
  "VE": { name: "Venezuela", zone: "Americas" },
  "VN": { name: "Vietnam", zone: "Asia" },
  "VU": { name: "Vanuatu", zone: "Oceania" },
  "WS": { name: "Samoa", zone: "Oceania" },
  "XK": { name: "Kosovo", zone: "Europe" },
  "YE": { name: "Yemen", zone: "Middle East" },
  "ZA": { name: "South Africa", zone: "Africa" },
  "ZM": { name: "Zambia", zone: "Africa" },
  "ZW": { name: "Zimbabwe", zone: "Africa" },
};

export const COUNTRIES: { code: string; name: string; zone: Zone }[] = Object.entries(COUNTRY_BY_ISO2)
  .map(([code, v]) => ({ code, name: v.name, zone: v.zone }))
  .sort((a, b) => a.name.localeCompare(b.name));

// A regenerated table once lost its keys (2026-09-15) and silently emptied
// the city picker; fail loudly at import instead.
if (COUNTRIES.length < 150) throw new Error('geo: COUNTRY_BY_ISO2 table is broken');
